### ISSUE TITLE
Winston does not appear to inject properly

### ISSUE THREAD

**Issue by Offlein** [gremo/nest-winston#2] opened 2018-11-24 21:36 UTC
Hi, I'm trying to Inject Winston into a service class. I've added Winston to the main Application module:
```
import { Module } from '@nestjs/common';
...
import { WinstonModule } from 'nest-winston';
import * as winston from "winston";

@Module({
    imports: [
        TypeOrmModule.forRoot(),
        WinstonModule.forRoot({
            level: 'info',
            format: winston.format.json(),
            transports: [
                //
                // - Write to all logs with level `info` and below to `combined.log`
                // - Write all logs error (and below) to `error.log`.
                //
                new winston.transports.File({ filename: 'error.log', level: 'error' }),
                new winston.transports.File({ filename: 'combined.log' })
            ]
        }),
        AuthModule,
        ...
    ]
})
```

and in its constructor I've built it like this:
```
...
import {Logger} from "winston";

@Injectable()
export class FileService {
    constructor(@InjectRepository(ImageFile)
                @Inject('winston') logger: Logger,
                private readonly imageFileRepository: Repository<ImageFile>,
                config: ConfigService,
    ) { ... }
```

However, upon startup, NestJS presents:
```
[Nest] 12572   - 11/24/2018, 4:33:15 PM   [ExceptionHandler] Nest can't resolve dependencies of the FileService (ImageFileRepository, ?, ConfigService). Please make sure that the argument at index [1] is available in the current context. +16ms
Error: Nest can't resolve dependencies of the FileService (ImageFileRepository, ?, ConfigService). Please make sure that the argument at index [1] is available in the current context.
```

So, it looks like the Winston injection isn't there. My understanding is that because I added Winston `.forRoot()` it should be ready to inject anywhere... Maybe the token is wrong?

Also, it appears that Winston will not operate without a specified config, I think? Maybe it should have a sensible default?

**Comment by gremo** [comment] 2018-12-02 10:15
I can't reproduce the bug. Can you setup a minmal complete example on a github repository?

**Comment by gremo** [comment] 2019-01-23 17:47
@ToJen what do you mean?

**Comment by ToJen** [comment] 2019-02-22 16:31
I want to import a module for my config to fetch environment variables, the same way I can in Mongoose:

```javascript
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        uri: configService.get('index.MONGODB_URI'),
        useNewUrlParser: true,
        useCreateIndex: true,
      }),
      inject: [ConfigService],
    }),
```

```javascript
    WinstonModule.forRootAsync({
      useFactory: async (configService: ConfigService) => ({
        format: winston.format.combine(
          winston.format.timestamp(),
          winston.format.printf(
            i =>
              `timestamp=${i.timestamp} level=${i.level} application=${configService.get('index.APPLICATION_NAME')} ${
                i.message
              }`,
          ),
        ),
        transports: [
          new winston.transports.File({
            level: configService.get('index.LOGGING_LEVEL'),
            filename: configService.get('index.LOG_FOLDER'),
            handleExceptions: true,
            json: configService.get('index.WINSTON_LOG_AS_JSON'),
            maxsize: configService.get('index.WINSTON_MAX_SIZE'),
            maxFiles: configService.get('index.WINSTON_MAX_FILES'),
            colorize: configService.get('index.WINSTON_COLORIZE'),
          } as any),
          new winston.transports.Console({
            level: configService.get('index.LOGGING_LEVEL'),
            handleExceptions: true,
            json: configService.get('index.WINSTON_LOG_AS_JSON'),
            colorize: true,
          } as any),
        ],
        exitOnError: false, // do not exit on handled exceptions
      }),
      inject: [ConfigService],
    }),
```

**Comment by achyutjhunjhunwala** [comment] 2019-03-18 00:19
@gremo I am too facing this issue. ConfigProperties are not getting resolved for WinstonModule.forRootAsync({})

**Comment by gremo** [comment] 2019-05-25 11:22
Closing, see https://github.com/gremo/nest-winston#async-configuration

**Comment by gremo** [comment] 2019-05-25 11:42
Nevermind... this is partially true, I'm going to implement `import` support with async configuration.

**Closed** 2019-05-25 11:50 UTC
